language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: 5.3
    - php: hhvm

before_script:
  # PHPCS
  - pyrus install pear/PHP_CodeSniffer
  # Composer
  - wget -nc http://getcomposer.org/composer.phar
  - php composer.phar install --dev --no-interaction

  # Dirs
  - mkdir -p build/logs
  - mkdir -p .reports

  - phpenv rehash

script:
  # PHPUnit tests
  - phpunit --configuration phpunit.xml --coverage-text --coverage-clover=.reports/clover.xml

after_script:
  - php vendor/bin/coveralls

notifications:
  email: false
