language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: 5.3
    - php: hhvm

before_script:
  # Composer
  - composer self-update

script:
  - mkdir .reports
  # PHPUnit tests
  - phpunit --configuration phpunit.xml --coverage-text --coverage-clover=.reports/clover.xml

notifications:
  email: false
