language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true

before_script:
  - composer update-all

script:
  - composer test

after_script:
  - composer coveralls

notifications:
  slack: jbzoo:lKYRTvAF36tRDfKTOK5zhFh9
