language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  # Composer
  - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source --dev install
  - composer self-update
  - composer update --prefer-source

script:
  - mkdir .reports
  # Code style
  - php vendor/bin/phpcs ./src --standard=PSR1 --encoding=utf-8 --report=summary
  - php vendor/bin/phpcs ./src --standard=PSR2 --encoding=utf-8 --report=summary
  # PHPUnit tests
  - phpunit --configuration phpunit.xml --coverage-text --coverage-clover=.reports/clover.xml

after_success:
  # Send cover
  - php vendor/bin/coveralls -v
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover .reports/clover.xml

notifications:
  email: false
