language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  # Composer
  - composer self-update
  - composer install --no-interaction

  # Dirs
  - mkdir -p build/logs
  - mkdir -p build/pdepend

  # Update env
  - phpenv rehash

script:
  # PHPUnit tests
  - php vendor/bin/phpunit --configuration phpunit.xml.dist

after_script:
  # Send to coveralls
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "5.5" ]; then
        php vendor/bin/coveralls -v;
    fi;'

  # Check PSR1,2 src and tests (NOT FOR HipHop !!!)
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "5.5" ]; then
        php vendor/bin/phpcs ./src   --standard=PSR1,PSR2 --encoding=utf-8 --report=summary -vp | grep "TOTAL\sOF";
        php vendor/bin/phpcs ./tests --standard=PSR2      --encoding=utf-8 --report=summary -vp | grep "TOTAL\sOF";
    fi;'
  
  # Try to find copy-paste
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "5.5" ]; then
        php vendor/bin/phpcpd ./src  --no-interaction --verbose;
    fi;'

  # Show code statistic
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "5.5" ]; then
        php vendor/bin/phploc ./src  --no-interaction --verbose;
    fi;'

  # Show code problems
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "5.5" ]; then
        php vendor/bin/phpmd ./src text codesize --verbose;
    fi;'

  # Build pdepend stats
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "5.5" ]; then
        php vendor/bin/pdepend
          --summary-xml=build/pdepend/summary.xml
          --jdepend-chart=build/pdepend/jdepend.svg
          --overview-pyramid=build/pdepend/pyramid.svg ./src;
    fi;'

notifications:
  email: denis@jbzoo.com
